# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sub', '0002_auto_20170414_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.CharField(blank=True, default='', max_length=15)),
                ('interests', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='qboxuser',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='qboxuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='qboxuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Qboxuser',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
