# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_sub', '0003_auto_20170417_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern',
            name='interests',
            field=models.TextField(max_length=100),
        ),
    ]
